"""empty message

Revision ID: 36185f524b28
Revises: 63061ffef967
Create Date: 2018-09-18 20:41:42.538350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36185f524b28'
down_revision = '63061ffef967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_testing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_mahasiswa', sa.Integer(), nullable=True),
    sa.Column('hasil', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_mahasiswa'], ['mahasiswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_testing')
    # ### end Alembic commands ###
