"""empty message

Revision ID: 4ea3fb916761
Revises: 0410d7c48df4
Create Date: 2018-08-29 15:19:58.964531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea3fb916761'
down_revision = '0410d7c48df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_mahasiswa', sa.Integer(), nullable=True),
    sa.Column('keterangan_lulus', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['id_mahasiswa'], ['mahasiswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_testing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_mahasiswa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_mahasiswa'], ['mahasiswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_training',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_alumni', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_alumni'], ['alumni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hasil',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_testing', sa.Integer(), nullable=True),
    sa.Column('hasil', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['id_testing'], ['data_testing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('nilai', sa.Column('IPK', sa.Float(), nullable=False))
    op.add_column('nilai', sa.Column('semester_1', sa.Float(), nullable=False))
    op.add_column('nilai', sa.Column('semester_2', sa.Float(), nullable=False))
    op.add_column('nilai', sa.Column('semester_3', sa.Float(), nullable=False))
    op.add_column('nilai', sa.Column('semester_4', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nilai', 'semester_4')
    op.drop_column('nilai', 'semester_3')
    op.drop_column('nilai', 'semester_2')
    op.drop_column('nilai', 'semester_1')
    op.drop_column('nilai', 'IPK')
    op.drop_table('hasil')
    op.drop_table('data_training')
    op.drop_table('data_testing')
    op.drop_table('alumni')
    # ### end Alembic commands ###
