"""empty message

Revision ID: 63061ffef967
Revises: ae9ea3f9e24b
Create Date: 2018-09-18 19:11:40.300492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63061ffef967'
down_revision = 'ae9ea3f9e24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hasil')
    op.add_column('data_testing', sa.Column('hasil', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_testing', 'hasil')
    op.create_table('hasil',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_testing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hasil', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_testing'], ['data_testing.id'], name='hasil_id_testing_fkey'),
    sa.PrimaryKeyConstraint('id', name='hasil_pkey')
    )
    # ### end Alembic commands ###
