"""empty message

Revision ID: 9c72079e7309
Revises: 9fc21edd6d21
Create Date: 2018-08-29 20:24:48.825190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c72079e7309'
down_revision = '9fc21edd6d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_mahasiswa', sa.Integer(), nullable=True),
    sa.Column('keterangan_lulus', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_mahasiswa'], ['mahasiswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'data_training', 'alumni', ['id_alumni'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_training', type_='foreignkey')
    op.drop_table('alumni')
    # ### end Alembic commands ###
