"""empty message

Revision ID: 9fc21edd6d21
Revises: bd3da39e22ab
Create Date: 2018-08-29 20:19:41.669326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc21edd6d21'
down_revision = 'bd3da39e22ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nilai',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_mahasiswa', sa.Integer(), nullable=True),
    sa.Column('semester_1', sa.String(length=1), nullable=False),
    sa.Column('semester_2', sa.String(length=1), nullable=False),
    sa.Column('semester_3', sa.String(length=1), nullable=False),
    sa.Column('semester_4', sa.String(length=1), nullable=False),
    sa.Column('ipk', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['id_mahasiswa'], ['mahasiswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nilai')
    # ### end Alembic commands ###
