"""empty message

Revision ID: b60dbed1eb49
Revises: 73e198bdbc7f
Create Date: 2018-08-29 16:57:52.963744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60dbed1eb49'
down_revision = '73e198bdbc7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahasiswa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('school_type', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('school_city', sa.String(length=10), nullable=False),
    sa.Column('parent_salary', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'alumni', 'mahasiswa', ['id_mahasiswa'], ['id'])
    op.create_foreign_key(None, 'data_testing', 'mahasiswa', ['id_mahasiswa'], ['id'])
    op.create_foreign_key(None, 'nilai', 'mahasiswa', ['id_mahasiswa'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nilai', type_='foreignkey')
    op.drop_constraint(None, 'data_testing', type_='foreignkey')
    op.drop_constraint(None, 'alumni', type_='foreignkey')
    op.drop_table('mahasiswa')
    # ### end Alembic commands ###
